---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "Travis.CI"
- git config --global user.email "travis@travis-ci.org"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="Fugiman/fugiman.github.io"
  - secure: "ikR2LbZ8byiqSRK4QjJiEG9JusdcIX3VpaD0BrJJCGyz0ZO8gYUJv3vruBE/yMVbBl30qhO7Q0a/FPZWLmgl3cM0hDgu3nBmvujOGit/FNUcgCX/byH1LACbIF5tAydD2X/q/Ajwy5tXrfhjfB4f1S/cnSTEI0626PwRMSBAf7o="
